config:
    paths:
        'oro/filter/dql-filter': 'bundles/okvpndqlfilter/js/filter/dql-filter.js'
        'okvpndqlfilter/js/views/dql-condition-view': 'bundles/okvpndqlfilter/js/dql-condition-view.js'
        'okvpndqlfilter/js/views/dql-view': 'bundles/okvpndqlfilter/js/dql-view.js'
        'oroquerydesigner/js/app/views/condition-builder/condition-builder-view': 'bundles/okvpndqlfilter/js/condition-builder/condition-builder-view.js'
        'oroquerydesigner/js/app/views/condition-builder/condition-builder-view-inner': 'bundles/oroquerydesigner/js/app/views/condition-builder/condition-builder-view.js'
