operations:
    segment_dql_help:
        label: About DQL
        acl_resource: dql_filter_management
        page_reload: false
        groups:
            - queryDesignerEditor
        button_options:
            template: OkvpnDqlFilterBundle:Segment:dqlAboutButton.html.twig
        datagrids: [fake-dql-grid]
        frontend_options:
            template: OkvpnDqlFilterBundle:Segment:dqlAbout.html.twig
            options:
                allowMaximize: false
                allowMinimize: false
                dblclick: maximize
                width: 780
                height: 40%
        attributes:
            empty:
                label: ' '
                type: string
        form_options:
            attribute_fields:
                empty:
                    form_type: text
